=== HippoInWindow20/hippoinwindow20.github.io/notice/format.dtd
<!ELEMENT doc (notice+)>
<!ELEMENT notice (title,date,author,authority,desc,link)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT authority (#PCDATA)>
<!ELEMENT desc (line+)>
<!ELEMENT line (#PCDATA)>
<!ELEMENT link (#PCDATA)>

=== HippoInWindow20/hippoinwindow20.github.io/notice/20220831.xml
<!DOCTYPE doc SYSTEM "format.dtd">
<doc>
        <notice>
                <title>111-1 高中社團網路選社說明 
</title>
                <date>2022/8/26
</date>
                <author>薛惟中
</author>
                <authority>學務處/職員
</authority>
                <desc>
                        <line>選社時間08/26 08:00-09/02 23:59</line>
                        <line>詳細內容如附件，若未於期限內選社，將由系統自動分發，請同學特別留意。</line>
                </desc>
                <link>https://drive.google.com/file/d/1xvKFdCD7NiS5qcjaqC5vpB9Ifx4aZCcm/view
</link>
        </notice>
        <notice>
                <title>關於圖書館夜自習，預約前請詳閱管理辦法，以免違規遭停權。 
</title>
                <date>2022/8/31
</date>
                <author>張淑婷
</author>
                <authority>圖書館/職員
</authority>
                <desc>
                        <line>※預約前請詳閱管理辦法，以免違規遭停權。※</line>

                        <line>請注意：</line>
                        <line>1.若在放學後至18:40之前使用圖書館自習的同學，請勿預約座位。</line>
                        <line>2.使用夜自習座位時間是指六點四十分 ~ 九點二十分，若於該時間之前會離開者，請勿預約占用座位。可至「暫時停留區」自習即可。</line>
                </desc>
                <link>https://proxy.yphs.tp.edu.tw/~op4/圖書館預約座位.htm
</link>
        </notice>
        <notice>
                <title>大學程式設計先修檢測(APCS)訂於111年10月23日舉辦，歡迎同學報名參加。 
</title>
                <date>2022/8/31
</date>
                <author>張淑婷
</author>
                <authority>圖書館/職員
</authority>
                <desc>
                        <line>一、旨揭檢測於111年8月30日至9月8日開放線上報名，因各地區試場座位有限，請提醒學生儘早報名以利選擇試場。</line>
                        <line>、本次檢測報名分二個時段：第一時段8月30日(星期二)至8月31日(星期三) 限高中(職)三年級生報名；第二時段9月1日(星期四)至9月8日(星期四) 不限對象報名。報名請至官網→「報名檢測」。</line>
                        <line>三、報名訊息及相關措施公告於APCS官網，請提醒學生詳閱公告內容，第一時段報名高中(職)三年級生須備妥指定的證明文件上傳。檢測開放單選科目報名，檢測時段上午為觀念題科目/二節次，下午為實作題科目/一節次。</line>
                        <line>四、試場設置於全國各地區大學，請詳見官網→「檢測資訊→試場資訊」。</line>
                        <line>五、因應防疫調整應測事宜將公告於官網(https://apcs.csie.ntnu.edu.tw)，敬請隨時關注。 </line>
                </desc>
                <link>https://apcs.csie.ntnu.edu.tw</link>
        </notice>
        <notice>
                <title>如有遺失國二程式設計課本的同學，請於9/2 17:00前填寫表單進行加購。 
</title>
                <date>2022/8/31
</date>
                <author>張淑婷
</author>
                <authority>圖書館/職員
</authority>
                <desc>
                        <line>如有遺失國二程式設計課本的同學，請於9/2 17:00前填寫表單進行加購。</line>
                        <line></line>
                        <line>表單連結公告於網路班級聯絡簿，請同學登入查看。 </line>
                </desc>
                <link></link>
        </notice>
        <notice>
                <title>【重要通知】英語實驗班甄選複試時間異動與補考資訊 
</title>
                <date>2022/8/31
</date>
                <author>連芳國
</author>
                <authority>外語中心/外語組長
</authority>
                <desc>
                        <line>1.9/2五 17:00-17:50初試考試 將在綜合大樓7樓 709 710 711教室舉行，若因班級停課或確診無法參加考試者， </line>
                        <line>國一同學於下周三9/7 17:00-17:50於綜合大樓10樓 外語教室1進行補考</line>
                        <line>/6 17:00-17:50於綜合大樓10樓 外語教室1進行補考</line>

                        <line>2.原定下周9/6-9/8之英語實驗班口試，將延至9/13-9/15中午時段於綜合大樓10樓外語教室舉行，口試名單將在9/12星期一中午公布在學校網站與外語中心門口請同學自行注意時間 </line>
                </desc>
                <link></link>
        </notice>
        <notice>
                <title>第二代國中校務行政系統報備請假流程說明 
</title>
                <date>2022/8/31
</date>
                <author>李富傑
</author>
                <authority>學務處/約聘職員
</authority>
                <desc>
                        <line>第二代國中校務行政系統登入方式由其他登入改版為單一身分驗證登入.登入後請假方式不變.假單列印後請家長及導師簽名後送交學務處銷假!</line>
                </desc>
                <link>https://drive.google.com/file/d/1nOxspU902QRCBi12BYw2pxL5Bq_FNzqf/view?usp=sharing</link>
        </notice>
        <notice>
                <title>本校高一新生繡學號說明 
</title>
                <date>2020/9/11
</date>
                <author>邱芳津
</author>
                <authority>學務處/職員
</authority>
                <desc>
                        <line>1.學號請繡8碼。</line>
                        <line>2.其他內容詳見附件。 </line>
                </desc>
                <link>https://proxy.yphs.tp.edu.tw/~ypb/NEWS/1090911.pdf
</link>
        </notice>
        <notice>
                <title>本校國一新生繡學號說明 
</title>
                <date>2022/6/7
</date>
                <author>邱芳津
</author>
                <authority>學務處/職員
</authority>
                <desc>
                        <line>1.學號請繡8碼。</line>
                        <line>2.其他內容詳見附件。 </line>
                </desc>
                <link>https://proxy.yphs.tp.edu.tw/~ypb/NEWS/1110321-11.pdf
</link>
        </notice>
        <notice>
                <title>(更新登入方式)本校新版高中校務行政系統學生線上報備請假操作說明 
</title>
                <date>2022/8/30
</date>
                <author>邱芳津
</author>
                <authority>學務處/職員
</authority>
                <desc>
                        <line>本校高中部學生請假請登入新版高中校務行政系統列印假單，操作方式請詳見附件。 </line>
                </desc>
                <link>https://proxy.yphs.tp.edu.tw/~ypb/NEWS/1110830.pdf
</link>
        </notice>
        <notice>
                <title>(更新國中新生登入方式)延平家長即時通上架了，歡迎使用 
</title>
                <date>2022/8/31
</date>
                <author>邱芳津
</author>
                <authority>學務處/職員
</authority>
                <desc>
                        <line>1.操作方式及內容請參考附件。</line>
                        <line>2.國中部舊生登入帳密如下</line>
                        <line>帳號：D或M+學生身分證字號,第一次登入</line>
                        <line>密碼為學生學號 (帳號共11碼,英文需大寫)</line>
                        <line>3.國中部111學年度新生登入帳密如下</line>
                        <line>帳號：P+學號</line>
                        <line>密碼第一次登入密碼為身分證字號(帳號共9碼,英文P需大寫)</line>
                        <line>4.高中部登入帳密為新版高中校務行政的帳號及密碼(帳號：P+學生學號,第一次登入密碼為學生身分證字號)。(帳號共9碼，英文需大寫）</line>
                        <line>5.若有疑問請洽生輔組27071478#2309。 </line>
                </desc>
                <link>https://proxy.yphs.tp.edu.tw/~ypb/NEWS/1110830.ppsx
</link>
        </notice>
        <notice>
                <title>「111學年度各重要人才培育計畫報名時程」完整版。更新師大化學 
</title>
                <date>2022/8/3
</date>
                <author>翁為宏
</author>
                <authority>教務處/設備組長
</authority>
                <desc>
                        <line>詳情如附件 </line>
                </desc>
                <link>https://drive.google.com/file/d/1CPVevdllgz_E49NsSHnNjGyuf1oNhG5T/view?usp=sharing
</link>
        </notice>
        <notice>
                <title>111學年度臺北市私立延平高級中學探究與實作競賽 
</title>
                <date>2022/8/8
</date>
                <author>翁為宏
</author>
                <authority>教務處/設備組長
</authority>
                <desc>
                        <line>一、參加對象：本校社會組及自然組學生，有修習過探究與實作者。歷屆有參加過此競賽且得獎者，請勿報名。</line>
                        <line>二、競賽及報名時間：</line>
                        <line>(一) 參賽學生須填寫推薦報名表暨切結書(如附件二)，並於111年9月12日(一) </line>
                        <line>中午12：20前交至教務處設備組。(每班至多3組)</line>
                        <line>(二) 參賽學生作品說明書及海報電子檔於111年9月30日(二)中午12：20前交至教務處設備組。(逾期視同棄權)</line>
                        <line>(三) 報名注意事項：繳交電子檔作品名稱需與報名表相同，不得更改。</line>
                        <line></line>
                        <line>詳情請見附件</line>

                </desc>
                <link>https://drive.google.com/file/d/1OkJ6cKM8wRQfZqJGF8i02voop-lnC90P/view?usp=sharing
</link>
        </notice>
        <notice>
                <title>2022年第19屆清華盃全國高級中學化學科能力競賽(報名已開始，保握機會) 
</title>
                <date>2022/8/9
</date>
                <author>翁為宏
</author>
                <authority>教務處/設備組長
</authority>
                <desc>
                        <line>一、參賽對象及名額：</line>
                        <line>(一) 參加對象：限各公、私立高中職各年級高中職生。</line>
                        <line>(二) 名額：限額 3,000 名(750 組)，以組為單位報名參賽，每組4 名學生。</line>
                        <line></line>
                        <line>二、報名相關：</line>
                        <line>(一)報名方式：採網路報名。</line>
                        <line>※本屆報名時不需填寫帶隊老師，晉級實驗決賽時才需提交。</line>
                        <line>※報名網址：主辦單位網站>清華盃報名系統>線上報名【報名流程詳見簡章附錄】</line>
                        <line>(二)報名日期：</line>
                        <line>111 年8 月30日(二)~111年9 月6日(二)止</line>
                        <line>【人數額滿，報名系統會自動提前截止報名】</line>
                        <line>※溫馨提醒：報名時間從8/30凌晨0點開始，去年至早上7點即額滿，請同學注意。</line>
                        <line>(三)報名費：</line>
                        <line>每組報名費新台幣 2,400 元整【請注意繳費期限，繳費成功才算報名成功】。 </line>
                        <line></line>
                        <line>三、競賽日期：</line>
                        <line>（一）筆試初賽：111年10月29日（星期六）下午1點。地點：國立清華大學。</line>
                        <line>(二) 實驗決賽：111年11月12日（星期六）上午8點30分。地點：國立清華大學。</line>
                        <line></line>
                        <line>詳情請務必參考附件簡章 </line>
                </desc>
                <link>https://drive.google.com/file/d/1snTgGASbQkL4VP5rGUY_j2s-4ZKmNLuv/view?usp=sharing</link>
        </notice>
</doc>
